env:
  node: true
  es2020: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:mocha/recommended'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - prettier
  - mocha
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  prettier/prettier:
    - error
  mocha/no-top-level-hooks:
    - off
  mocha/no-exports:
    - off
  mocha/max-top-level-suites:
    - off
