version: '3.9'
services:
  clamav:
    image: mkodockx/docker-clamav:latest
    networks:
      - scan-upload
    healthcheck:
      test: ['CMD', './check.sh']
      interval: 60s
      retries: 3
      start_period: 120s
  server:
    build: .
    networks:
      - scan-upload
    ports:
      - '127.0.0.1:3500:3500'
    volumes:
      - ../:/app/
    depends_on:
      - clamav

networks:
  scan-upload:
    driver: bridge
